
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ODSAPISoap", targetNamespace = "http://tempuri.org/")
public interface ODSAPISoap {


    /**
     * 
     * @param msisdn
     * @return
     *     returns int
     */
    @WebMethod(operationName = "DeactivateDial", action = "http://tempuri.org/DeactivateDial")
    @WebResult(name = "DeactivateDialResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DeactivateDial", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeactivateDial")
    @ResponseWrapper(localName = "DeactivateDialResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeactivateDialResponse")
    public int deactivateDial(
        @WebParam(name = "MSISDN", targetNamespace = "http://tempuri.org/")
        String msisdn);

}
