
package org.tempuri;


import java.net.URL;
import java.util.List;

import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.handler.Handler;

import com.etisalat.disconnection.provisioning.WebServiceHandler;



/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "ODSAPI", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/D:/Sources/Programing/Jboss/jboss-5.1.0.GA/jboss-5.1.0.GA/bin/ODSAPI.asmx.xml")
public class ODSAPI
    extends Service
{

    
//    private final static Logger logger = Logger.getLogger(org.tempuri.ODSAPI.class.getName());

    

    public ODSAPI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }
    
    
    public ODSAPI(URL wsdlLocation) {
        super(wsdlLocation, new QName("http://tempuri.org/", "ODSAPI"));
    }

	// public ODSAPI() {
	// super(ODSAPI_WSDL_LOCATION, new QName("http://tempuri.org/", "ODSAPI"));
	// }

    /**
     * 
     * @return
     *     returns ODSAPISoap
     */
    @WebEndpoint(name = "ODSAPISoap")
    public ODSAPISoap getODSAPISoap() {
    	
    	ODSAPISoap port = super.getPort(new QName("http://tempuri.org/", "ODSAPISoap"), ODSAPISoap.class);

		BindingProvider provider = (BindingProvider) port;

		provider.getRequestContext().put(
				"com.sun.xml.internal.ws.request.timeout", 10000);
		provider.getRequestContext().put(
				"com.sun.xml.internal.ws.connect.timeout", 10000);
		
		
		
		List<Handler> handlerChain = provider.getBinding().getHandlerChain();
		handlerChain.add(new WebServiceHandler());
		provider.getBinding().setHandlerChain(handlerChain);

		return port;
    	
    	
        
    }

}
